import { Theme } from '@/styles/theme';
import { StyleSheet } from 'react-native';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    reauthOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.6)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    reauthDialog: {
      width: '100%',
      maxWidth: 400,
      borderRadius: 12,
      padding: 24,
      backgroundColor: theme.colors.modalBackground,
    },
    reauthTitle: {
      fontSize: 18,
      fontWeight: '700',
      marginBottom: 8,
      color: theme.colors.text,
    },
    reauthMessage: {
      fontSize: 14,
      marginBottom: 16,
      color: theme.colors.textSecondary,
    },
    reauthInput: {
      borderWidth: 1,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 16,
      marginBottom: 8,
      color: theme.colors.text,
      borderColor: theme.colors.border,
    },
    reauthErrorText: {
      fontSize: 13,
      marginBottom: 8,
      color: theme.colors.error,
    },
    reauthButtonRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 12,
      marginTop: 8,
    },
    reauthCancelButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
    },
    reauthCancelText: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.textSecondary,
    },
    reauthDeleteButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 8,
      backgroundColor: theme.colors.error,
    },
    reauthDeleteButtonText: {
      color: '#fff',
      fontSize: 16,
      fontWeight: '700',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      width: '90%',
      maxWidth: 450,
      backgroundColor: theme.colors.modalBackground,
      borderRadius: 12,
      height: '80%',
      overflow: 'hidden',
    },
    container: {
      flex: 1,
    },
    scrollContent: {
      padding: 20,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: 'bold',
      marginBottom: 15,
      textAlign: 'center',
      color: theme.colors.text,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '600',
      marginTop: 20,
      marginBottom: 10,
      color: theme.colors.text,
    },
    sectionDivider: {
      height: 1,
      backgroundColor: theme.colors.border,
      marginVertical: 20,
    },
    buttonRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      padding: 20,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      backgroundColor: theme.colors.modalBackground,
    },
    logoutSection: {
      marginTop: 24,
      marginBottom: 16,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      paddingTop: 16,
    },
    feedbackButton: {
      backgroundColor: theme.colors.primary + '15',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginTop: 8,
      borderWidth: 1,
      borderColor: theme.colors.primary,
      alignItems: 'center',
    },
    feedbackButtonText: {
      color: theme.colors.primary,
      fontWeight: '600',
      fontSize: 16,
    },
    logoutButton: {
      backgroundColor: theme.colors.error + '15',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginTop: 8,
      borderWidth: 1,
      borderColor: theme.colors.error,
      alignItems: 'center',
    },
    logoutText: {
      color: theme.colors.error,
      fontWeight: '600',
      fontSize: 16,
    },
    deleteAccountButton: {
      backgroundColor: theme.colors.error + '20',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginTop: 8,
      borderWidth: 2,
      borderColor: theme.colors.error,
      alignItems: 'center',
    },
    deleteAccountText: {
      color: theme.colors.error,
      fontWeight: '700',
      fontSize: 16,
    },
  });
