import { Difficulty } from '@/src/utils/constants';

export type Exercise = {
  name: string;
  category: 'upper' | 'lower' | 'mobility';
  duration: number;
  videoUrl?: string | null;
  equipment?: string[] | null;
  difficulty: Difficulty[];
  instructions: string[];
  isBilateral?: boolean;
};

export const exercises: Exercise[] = [
  // UPPER STRENGTH EXERCISES
  {
    name: 'Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
    instructions: [
      'Start in a plank position with hands slightly wider than shoulders',
      'Keep your body in a straight line from head to heels',
      'Lower your chest toward the ground by bending your elbows',
      'Push back up to the starting position, fully extending your arms',
    ],
  },
  {
    name: 'Incline Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy'],
    instructions: [
      'Place your hands on a desk or sturdy surface at waist height',
      'Walk your feet back to create an inclined plank position',
      'Lower your chest toward the surface by bending your elbows',
      'Push back up to the starting position, maintaining straight body alignment',
    ],
  },
  {
    name: 'Decline Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
    instructions: [
      'Place your feet on a desk or sturdy surface at waist height',
      'Get into a plank position with hands on the ground',
      'Lower your chest toward the ground by bending your elbows',
      'Push back up to the starting position, keeping your core engaged',
    ],
  },
  {
    name: 'Diamond Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
    instructions: [
      'Start in a plank position with hands close together, thumbs and index fingers forming a diamond',
      'Keep your body in a straight line and core engaged',
      'Lower your chest toward your hands by bending your elbows',
      'Push back up to the starting position, focusing on tricep engagement',
    ],
  },
  {
    name: 'Pike Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
    instructions: [
      'Start in a downward dog position with hands shoulder-width apart',
      'Keep your legs straight and hips high, forming an inverted V shape',
      'Lower your head toward the ground by bending your elbows',
      'Push back up to the starting position, focusing on shoulder strength',
    ],
  },
  {
    name: 'Chair Dips',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Sit on the edge of a sturdy chair with hands gripping the seat',
      'Slide forward so your body is off the chair, supporting your weight with your arms',
      'Lower your body by bending your elbows to about 90 degrees',
      'Push back up to the starting position, fully extending your arms',
    ],
  },
  {
    name: 'Pull-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: ['Pull-up Bar'],
    difficulty: ['medium', 'hard'],
    instructions: [
      'Hang from a pull-up bar with hands slightly wider than shoulder-width apart',
      'Engage your core and keep your body straight',
      'Pull your body up until your chin clears the bar',
      'Lower yourself back down with control to the starting position',
    ],
  },
  {
    name: 'Scapular Pull-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: ['Pull-up Bar'],
    difficulty: ['easy'],
    instructions: [
      'Hang from a pull-up bar with arms fully extended',
      'Keep your arms straight and engage your shoulder blades',
      'Pull your shoulder blades down and back without bending your elbows',
      'Hold the position briefly, then return to the starting position',
    ],
  },
  {
    name: 'TRX Rows',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: ['TRX'],
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Hold the TRX handles and lean back at an angle with arms extended',
      'Keep your body in a straight line from head to heels',
      'Pull your chest toward the handles by squeezing your shoulder blades',
      'Return to the starting position with control, maintaining tension',
    ],
  },
  {
    name: 'Wall Handstand',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
    instructions: [
      'Start in a downward dog position with your back to a wall',
      'Walk your feet up the wall while walking your hands closer to the wall',
      'Continue until your body is in a vertical handstand position against the wall',
      'Hold the position, engaging your core and shoulders for stability',
    ],
  },
  {
    name: 'Handstand Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
    instructions: [
      'Start in a wall handstand position with hands shoulder-width apart',
      'Keep your body straight and core engaged',
      'Lower your head toward the ground by bending your elbows',
      'Push back up to the starting handstand position',
    ],
  },
  {
    name: 'Archer Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
    instructions: [
      'Start in a wide push-up position with hands much wider than shoulders',
      'Keep your body in a straight line and core engaged',
      'Lower your chest toward one hand while keeping the other arm straight',
      'Push back up and alternate sides, shifting weight between arms',
    ],
  },

  // LOWER STRENGTH EXERCISES
  {
    name: 'Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium'],
    instructions: [
      'Stand with feet shoulder-width apart and toes slightly pointed out',
      'Keep your chest up and core engaged',
      'Lower your body by bending your knees and pushing your hips back',
      'Push through your heels to return to the starting position',
    ],
  },
  {
    name: 'Chair Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy'],
    instructions: [
      'Stand in front of a chair with feet shoulder-width apart',
      'Keep your chest up and arms extended in front of you',
      'Lower your body until you lightly touch the chair seat',
      'Push through your heels to return to the starting position',
    ],
  },
  {
    name: 'Pistol Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
    instructions: [
      'Stand on one leg with the other leg extended in front of you',
      'Extend your arms forward for balance',
      'Lower your body by bending the standing leg while keeping the other leg straight',
      'Push through your heel to return to the starting position',
    ],
  },
  {
    name: 'Kossack Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
    instructions: [
      'Stand with feet wider than shoulder-width apart, toes pointed out',
      'Shift your weight to one leg while keeping the other leg straight',
      'Lower your body by bending the weighted leg while keeping the other leg extended',
      'Push through your heel to return to the starting position and alternate sides',
    ],
  },
  {
    name: 'Lunges',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium'],
    instructions: [
      'Stand with feet hip-width apart and hands on hips',
      'Step forward with one leg, lowering your body until both knees are at 90 degrees',
      'Keep your front knee over your ankle and back knee hovering above the ground',
      'Push through your front heel to return to the starting position',
    ],
  },
  {
    name: 'Glute Bridge',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium'],
    instructions: [
      'Lie on your back with knees bent and feet flat on the ground',
      'Place your arms at your sides with palms down',
      'Lift your hips up by squeezing your glutes and pushing through your heels',
      'Lower your hips back down to the starting position with control',
    ],
  },
  {
    name: 'Hamstring Floor Slide',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
    instructions: [
      'Lie on your back with knees bent and feet on smooth floor or paper',
      'Lift your hips up into a bridge position',
      'Slowly slide your feet away from your body, straightening your legs',
      'Slide your feet back to the starting position while maintaining the bridge',
    ],
  },
  {
    name: 'Calf Raises',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Stand with feet hip-width apart, holding onto a desk or wall for balance',
      'Keep your knees slightly bent and core engaged',
      'Rise up onto your toes by lifting your heels off the ground',
      'Lower your heels back down to the starting position with control',
    ],
  },
  {
    name: 'Wall Sit',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
    instructions: [
      'Stand with your back against a wall and feet shoulder-width apart',
      'Slide down the wall until your knees are at 90 degrees',
      'Keep your back flat against the wall and core engaged',
      'Hold the position, ensuring your knees are directly above your ankles',
    ],
  },

  // MOBILITY EXERCISES
  {
    name: 'Arm Circles',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Stand with feet shoulder-width apart and arms extended to the sides',
      'Keep your shoulders relaxed and core engaged',
      'Make large circular motions with your arms, moving forward',
      'Reverse direction and continue the circular motion',
    ],
  },
  {
    name: 'Hip Circles',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Stand with feet hip-width apart and hands on hips',
      'Keep your upper body stable and core engaged',
      'Move your hips in large circular motions, keeping your knees slightly bent',
      'Reverse direction and continue the circular motion',
    ],
  },
  {
    name: 'Leg Swings',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Stand next to a desk or wall for support with one hand',
      'Keep your standing leg slightly bent and core engaged',
      'Swing your free leg forward and backward in a controlled motion',
      'Switch legs and repeat the swinging motion',
    ],
    isBilateral: true,
  },
  {
    name: 'Chest Opener Stretch',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Stand in a doorway with arms on the doorframe in an "L" shape',
      'Keep your shoulders relaxed and core engaged',
      'Gently press your torso forward, opening your chest and squeezing your shoulder blades',
      'Hold the stretch and breathe deeply, feeling the stretch across your chest',
    ],
  },
  {
    name: 'Cat-Cow Stretch',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Start on your hands and knees in a tabletop position',
      'Arch your back and lift your chest and tailbone (Cow position)',
      'Round your spine and tuck your chin to your chest (Cat position)',
      'Flow smoothly between the two positions, breathing with each movement',
    ],
  },
  {
    name: 'Elephant Walks',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Start in a forward fold with hands on the ground and knees slightly bent',
      'Keep your hands planted gently straighten one leg until you feel a stretch',
      'Hold for a few seconds, then switch legs and repeat',
      'If the stretch is too intense, you can elevate your hands on a step or chair',
    ],
  },
  {
    name: 'Spinal Twists',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Sit on the ground with legs extended and back straight',
      'Bend your right knee and place your right foot outside your left knee',
      'Place your left elbow on the outside of your right knee and twist your torso',
      'Hold the stretch and breathe deeply, then switch sides',
    ],
    isBilateral: true,
  },
  {
    name: '90/90 Stretch',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Sit on the ground with your right leg bent at 90 degrees in front of you',
      'Place your left leg bent at 90 degrees to your left side',
      'Keep your back straight and lean forward over your right leg',
      'Hold the stretch and breathe deeply, then switch leg positions',
    ],
    isBilateral: true,
  },
  {
    name: "World's Greatest Stretch",
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Start in a lunge position with your right foot forward and left leg extended back',
      'Place your right hand on the ground inside your right foot',
      'Place your left hand on the ground and rotate your torso to the right',
      'Hold the stretch and breathe deeply, then switch sides',
    ],
    isBilateral: true,
  },
  {
    name: 'Couch Stretch',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
    instructions: [
      'Kneel in front of a wall with your right knee on the ground',
      'Place your right foot on the wall behind you',
      'Keep your left foot flat on the ground and your torso upright',
      'Hold the stretch and breathe deeply, then switch legs',
    ],
    isBilateral: true,
  },
];
