import { Difficulty } from '@/src/utils/constants';

export type Exercise = {
  name: string;
  category: 'upper' | 'lower' | 'full' | 'mobility';
  duration: number;
  videoUrl?: string | null;
  equipment?: string[] | null;
  difficulty: Difficulty[];
};

export const exercises: Exercise[] = [
  {
    name: 'Jumping Jacks',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium'],
  },
  {
    name: 'Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
  },
  {
    name: 'Incline Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy'],
  },
  {
    name: 'Archer Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
  },
  {
    name: 'Chair Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy'],
  },
  {
    name: 'Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium'],
  },
  {
    name: 'Kossack Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
  },
  {
    name: 'High Knees',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
  },
  {
    name: 'Knee Plank',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy'],
  },
  {
    name: 'Plank',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium'],
  },
  {
    name: 'Super Plank',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
  },
  {
    name: 'Lunges',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium'],
  },
  {
    name: 'Burpees',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
  },
  {
    name: 'Mountain Climbers',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
  },
  {
    name: 'Glute Bridge',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium'],
  },
  {
    name: 'Slider Hamstring Curls',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
  },
  {
    name: 'Arm Circles',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
  },
  {
    name: 'Hip Circles',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
  },
  {
    name: 'TRX Rows',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: ['TRX'],
    difficulty: ['easy', 'medium', 'hard'],
  },
  {
    name: 'Scapular Pull-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: ['Pull-up Bar'],
    difficulty: ['easy'],
  },
  {
    name: 'Pull-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: ['Pull-up Bar'],
    difficulty: ['medium', 'hard'],
  },
  {
    name: 'Calf Raises',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
  },
  {
    name: 'Jump Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['hard'],
  },
  {
    name: 'Bicycle Crunches',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
  },
  {
    name: 'Leg Swings',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
  },
  {
    name: 'Chest Opener Stretch',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
  },
  {
    name: 'Triceps Dips',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
  },
  {
    name: 'Cat-Cow Stretch',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
  },
  {
    name: 'Wall Sit',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
  },
  {
    name: 'Wall Handstand',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['medium', 'hard'],
  },
  {
    name: 'Elephant Walks',
    category: 'mobility',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: ['easy', 'medium', 'hard'],
  },
];
