export type Difficulty = 'easy' | 'medium' | 'hard';

export type Exercise = {
  name: string;
  category: 'upper' | 'lower' | 'full' | 'mobility';
  duration: number;
  videoUrl?: string | null;
  equipment?: string[] | null;
  difficulty: Difficulty;
};

export const exercises: Exercise[] = [
  {
    name: 'Jumping Jacks',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'easy',
  },
  {
    name: 'Push-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'medium',
  },
  {
    name: 'Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'easy',
  },
  {
    name: 'High Knees',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'medium',
  },
  {
    name: 'Plank',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'hard',
  },
  {
    name: 'Lunges',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'medium',
  },
  {
    name: 'Burpees',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'hard',
  },
  {
    name: 'Mountain Climbers',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'medium',
  },
  {
    name: 'Side Plank',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'hard',
  },
  {
    name: 'Glute Bridge',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'easy',
  },
  {
    name: 'Arm Circles',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: 'easy',
  },
  {
    name: 'Hip Circles',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: 'easy',
  },
  {
    name: 'TRX Rows',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: ['trx'],
    difficulty: 'medium',
  },
  {
    name: 'Pull-ups',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: ['pullup-bar'],
    difficulty: 'hard',
  },
  {
    name: 'Calf Raises',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'easy',
  },
  {
    name: 'Jump Squats',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'hard',
  },
  {
    name: 'Shoulder Taps',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'medium',
  },
  {
    name: 'Step-Ups',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'medium',
  },
  {
    name: 'Bicycle Crunches',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'medium',
  },
  {
    name: 'Leg Swings',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: 'easy',
  },
  {
    name: 'Chest Opener Stretch',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: 'easy',
  },
  {
    name: 'Triceps Dips',
    category: 'upper',
    duration: 30,
    videoUrl: null,
    equipment: ['chair'],
    difficulty: 'medium',
  },
  {
    name: 'Side Lunges',
    category: 'lower',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'medium',
  },
  {
    name: 'Jump Rope (imaginary)',
    category: 'full',
    duration: 30,
    videoUrl: null,
    equipment: null,
    difficulty: 'hard',
  },
  {
    name: 'Cat-Cow Stretch',
    category: 'mobility',
    duration: 60,
    videoUrl: null,
    equipment: null,
    difficulty: 'easy',
  },
];
