import { Theme } from '@/styles/theme';
import { StyleSheet } from 'react-native';

export const analyticsModalStyles = (theme: Theme) =>
  StyleSheet.create({
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      width: '90%',
      maxWidth: 450,
      backgroundColor: theme.colors.modalBackground,
      borderRadius: 12,
      height: '80%',
      overflow: 'hidden',
    },
    container: {
      flex: 1,
    },
    scrollContent: {
      padding: 20,
    },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 20,
    },
    modalTitle: {
      fontSize: 24,
      fontWeight: 'bold',
      marginLeft: 8,
      color: theme.colors.text,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      marginTop: 16,
      fontSize: 16,
      color: theme.colors.text,
    },
    section: {
      marginBottom: 24,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: '600',
      marginLeft: 8,
      color: theme.colors.text,
    },
    focusSection: {
      backgroundColor: theme.colors.primary + '15',
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderLeftWidth: 4,
      borderLeftColor: theme.colors.primary,
    },
    workoutSection: {
      backgroundColor: theme.colors.secondary + '15',
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderLeftWidth: 4,
      borderLeftColor: theme.colors.secondary,
    },
    metricsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    metricCard: {
      width: '48%',
      backgroundColor: theme.colors.card + 'CC',
      borderRadius: 8,
      padding: 12,
      marginBottom: 8,
      alignItems: 'center',
    },
    metricNumber: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.colors.text,
      marginBottom: 4,
    },
    metricLabel: {
      fontSize: 12,
      color: theme.colors.text + '80',
      textAlign: 'center',
    },
    achievementsSection: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      padding: 16,
      marginBottom: 16,
      borderLeftWidth: 4,
      borderLeftColor: '#FFD700',
    },
    achievementsCarousel: {
      paddingHorizontal: 8,
    },
    achievementCard: {
      backgroundColor: theme.colors.card,
      borderRadius: 8,
      padding: 12,
      marginHorizontal: 4,
      alignItems: 'center',
      minWidth: 120,
      shadowColor: theme.colors.text,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    achievementIcon: {
      marginBottom: 8,
    },
    achievementEmoji: {
      fontSize: 24,
      marginBottom: 4,
    },
    achievementText: {
      fontSize: 12,
      color: theme.colors.text,
      textAlign: 'center',
      fontWeight: '500',
    },
    noAchievementsContainer: {
      alignItems: 'center',
      paddingVertical: 20,
    },
    noAchievementsText: {
      fontSize: 14,
      color: theme.colors.text + '80',
      textAlign: 'center',
      fontStyle: 'italic',
    },
    statsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    statCard: {
      width: '48%',
      backgroundColor: theme.colors.primary + '15',
      padding: 16,
      borderRadius: 12,
      alignItems: 'center',
      marginBottom: 12,
    },
    statNumber: {
      fontSize: 24,
      fontWeight: 'bold',
      color: theme.colors.primary,
      marginBottom: 4,
    },
    statLabel: {
      fontSize: 12,
      color: theme.colors.text + '80',
      textAlign: 'center',
    },
    streakContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    streakItem: {
      alignItems: 'center',
      backgroundColor: theme.colors.secondary + '15',
      padding: 20,
      borderRadius: 12,
      flex: 1,
      marginHorizontal: 8,
    },
    streakNumber: {
      fontSize: 32,
      fontWeight: 'bold',
      color: theme.colors.secondary,
      marginBottom: 8,
    },
    streakLabel: {
      fontSize: 14,
      color: theme.colors.text + '80',
      textAlign: 'center',
    },
    averageContainer: {
      flexDirection: 'row',
      justifyContent: 'space-around',
    },
    averageItem: {
      alignItems: 'center',
      backgroundColor: theme.colors.accent + '15',
      padding: 16,
      borderRadius: 12,
      flex: 1,
      marginHorizontal: 8,
    },
    averageNumber: {
      fontSize: 20,
      fontWeight: 'bold',
      color: theme.colors.accent,
      marginBottom: 4,
    },
    averageLabel: {
      fontSize: 12,
      color: theme.colors.text + '80',
      textAlign: 'center',
    },
    activityContainer: {
      backgroundColor: theme.colors.surface,
      borderRadius: 12,
      padding: 16,
    },
    activityItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 8,
    },
    activityLabel: {
      fontSize: 14,
      color: theme.colors.text + '80',
    },
    activityValue: {
      fontSize: 14,
      fontWeight: '500',
      color: theme.colors.text,
    },
    buttonRow: {
      padding: 20,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
      backgroundColor: theme.colors.modalBackground,
    },
    closeButton: {
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '600',
      color: theme.colors.primary,
      paddingVertical: 12,
    },
  });
